### ISSUE TITLE
How fast does the rich presence update?

### ISSUE THREAD

**Issue by lamsmallcritter** [Harmon758/mb_DiscordRichPresence#4]

**Comment by Harmon758** [comment]
It's updated every time the track changes or is paused/unpaused.
In regards to rate limit concerns, per the [documentation](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence),
> `Discord_UpdatePresence()` has a rate limit of one update per 15 seconds. Developers do not need to do anything to handle this rate limit. The SDK will queue up any presence updates sent in that window and send the newest one once the client is free to do so. If you are sending presence updates very frequently and wondering why you don't see your Discord presence changing, that's why!
